import * as stylex from "@stylexjs/stylex";
import { breakpoints } from "@/styles/constants.stylex";
import {
	border,
	color,
	fontSize,
	fontWeight,
	letterSpacing,
	lineHeight,
	radius,
	shadow,
	size,
	space,
} from "@/styles/tokens.stylex";

const activeDropTarget = ":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])";
const invalidTarget = ":is([data-invalid], [data-invalid='true'], [data-invalid=''])";

export const demoStyles = stylex.create({
	stack: {
		gap: space.x5,
		display: "grid",
	},
	comparison: {
		gap: space.x5,
		alignItems: "start",
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.md]: "repeat(2, minmax(0, 1fr))",
		},
	},
	panel: {
		padding: space.x4,
		borderColor: color.border,
		borderRadius: radius.md,
		borderStyle: "solid",
		borderWidth: border.width,
		gap: space.x4,
		backgroundColor: color.surface,
		display: "grid",
		minWidth: 0,
	},
	panelHeader: {
		gap: space.x1,
		display: "grid",
	},
	panelFooter: {
		gap: space.x3,
		alignItems: "center",
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "space-between",
	},
	instructions: {
		margin: 0,
		gap: space.x1,
		color: color.fgMuted,
		fontSize: fontSize.x1,
		lineHeight: lineHeight.x1,
	},
	instructionItem: {
		display: "list-item",
		listStylePosition: "inside",
		listStyleType: "auto",
		paddingInlineStart: space.x5,
	},
	status: {
		margin: 0,
		color: color.fgMuted,
		fontSize: fontSize.x1,
		lineHeight: lineHeight.x1,
	},
	workArea: {
		gap: space.x4,
		display: "grid",
	},
	transferGrid: {
		gap: space.x3,
		alignItems: "stretch",
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.sm]: "minmax(12rem, 0.9fr) repeat(2, minmax(10rem, 1fr))",
		},
	},
	sourceTray: {
		gap: space.x3,
		alignContent: "start",
		display: "grid",
		minHeight: "7rem",
	},
	card: {
		padding: space.x2,
		borderRadius: radius.sm,
		gap: space.x3,
		alignItems: "center",
		backgroundColor: color.bgElevated,
		boxShadow: {
			default: shadow.sm,
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": "none",
			":hover": shadow.md,
		},
		color: color.fg,
		display: "flex",

		opacity: {
			default: 1,
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": 0.6,
		},
		touchAction: "none",
		transitionDuration: {
			default: "160ms",
			"@media (prefers-reduced-motion: reduce)": "0ms",
		},
		// transform: {
		// 	default: "none",
		// 	":is([data-dragging], [data-dragging='true'], [data-dragging=''])": "rotate(2deg)",
		// },
		transitionProperty: "background-color, border-color, box-shadow, opacity",
		transitionTimingFunction: "ease",
		minHeight: "3.25rem",
	},
	cardText: {
		gap: space.x1,
		display: "grid",
		flexGrow: 1,
		minWidth: 0,
	},
	cardLabel: {
		overflow: "hidden",
		fontSize: fontSize.x2,
		fontWeight: fontWeight.medium,
		lineHeight: lineHeight.x2,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	cardMeta: {
		color: color.fgMuted,
		fontSize: fontSize.x1,
		lineHeight: lineHeight.x1,
	},
	handle: {
		padding: 0,
		borderColor: color.border,
		borderRadius: radius.sm,
		borderStyle: "solid",
		borderWidth: border.width,
		alignItems: "center",
		color: color.fgMuted,
		cursor: {
			default: "grab",
			":active": "grabbing",
		},
		display: "inline-flex",
		justifyContent: "center",
		justifySelf: "flex-end",
		marginInlineStart: "auto",
		height: size["control.md"],
		width: size["control.md"],
	},
	dropZone: {
		padding: space.x4,
		borderRadius: radius.md,
		gap: space.x2,
		alignItems: "stretch",
		backgroundColor: {
			[activeDropTarget]: color.bgAccentSoft,
			default: color.surfaceSubtle,
			[invalidTarget]: color.bgDangerSubtle,
		},
		color: color.fg,
		display: "flex",
		flexDirection: "column",
		outlineColor: {
			[activeDropTarget]: color.bgAccent,
			default: color.border,
			[invalidTarget]: color.bgDanger,
		},
		outlineOffset: -border.width,
		outlineStyle: "dashed",
		outlineWidth: "1px",
		minHeight: "7rem",
	},
	dropZoneLabel: {
		fontSize: fontSize.x2,
		fontWeight: fontWeight.medium,
		lineHeight: lineHeight.x2,
	},
	dropZoneDescription: {
		color: color.fgMuted,
		fontSize: fontSize.x1,
		lineHeight: lineHeight.x1,
	},
	invalidLabel: {
		color: color.fgDanger,
	},
	board: {
		gap: space.x3,
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.sm]: "repeat(2, minmax(0, 1fr))",
		},
	},
	column: {
		padding: space.x3,
		borderRadius: radius.md,
		gap: space.x3,
		alignContent: "start",
		backgroundColor: {
			default: color.canvasSubtle,
			// ":where([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": color.highlight,
		},
		display: "grid",
		outlineColor: {
			default: color.border,
			":focus-within": color.bgAccent,
		},
		outlineOffset: -border.width,
		outlineStyle: "solid",
		outlineWidth: border.width,
		minHeight: "18rem",
	},
	columnHeader: {
		gap: space.x2,
		alignItems: "center",
		display: "flex",
		justifyContent: "space-between",
	},
	columnTitle: {
		fontSize: fontSize.x2,
		fontWeight: fontWeight.semibold,
		lineHeight: lineHeight.x2,
	},
	columnCount: {
		color: color.fgMuted,
		fontSize: fontSize.x1,
		lineHeight: lineHeight.x1,
	},
	list: {
		margin: 0,
		padding: 0,
		gap: space.x2,
		listStyle: "none",
		display: "flex",
		flexDirection: "column",
		minHeight: "12rem",
	},
	empty: {
		// padding: space.x3,
		// borderColor: color.fg,
		// backgroundColor: color.highlight,
		// borderRadius: radius.sm,
		// borderStyle: "dashed",
		// borderWidth: border.width,
		height: "100%",
		// alignItems: "center",
		// color: color.fgMuted,
		// display: "flex",
		// fontSize: fontSize.x1,
		// justifyContent: "center",
		// lineHeight: lineHeight.x1,
		// textAlign: "center",
		// minHeight: "4rem",
	},
	dropIndicator: {
		// borderRadius: radius.full,
		// marginInline: `-${space.x2}`,
		// width: `calc(100% + ${space.x2})`,
		// outline: `1px solid ${color.bgAccent}`,
		// outlineColor: color.bgAccent,
		// outlineColor: "CanvasText",
		outlineStyle: {
			default: "none",
			"@media (forced-colors: active)": "solid",
		},
		outlineWidth: {
			default: 0,
			"@media (forced-colors: active)": "1px",
		},
		position: "relative",
		zIndex: 100,
		height: "0px",
		"::before": {
			borderRadius: radius.full,
			insetBlock: -2,
			insetInline: -16,
			backgroundColor: color.bgAccent,
			content: "",
			outlineColor: color.fgAccentContrast,
			// outlineOffset: 2,
			outlineStyle: "solid",
			outlineWidth: 2,
			position: "absolute",
			minWidth: "100%",
		},
	},
	overlay: {
		boxShadow: shadow.lg,
		pointerEvents: "none",
		transform: "rotate(1deg)",
	},
	shortList: {
		gap: space.x2,
		display: "grid",
		maxWidth: "24rem",
	},
	menuDemo: {
		alignItems: "start",
		columnGap: `calc(${space.x8} * 4)`,
		display: "flex",
		flexWrap: "wrap",
		position: "relative",
		rowGap: space.x3,
		minHeight: "18rem",
	},
	sortableMenuPopup: {
		outlineColor: {
			default: "transparent",
			":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": color.fgMuted,
		},
		outlineOffset: "4px",
		outlineStyle: "dashed",
		outlineWidth: "2px",
		minWidth: "12rem",
	},
	sortableMenuItem: {
		opacity: {
			default: 1,
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": 0.58,
		},
		outlineColor: {
			default: "transparent",
			":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": color.fg,
		},
		outlineOffset: "2px",
		outlineStyle: "dashed",
		outlineWidth: "2px",
	},
	emptyMenuItem: {
		color: color.fgMuted,
		fontStyle: "italic",
		display: "flex",
		outlineStyle: "dashed",
		outlineWidth: "1px",
		outlineColor: color.borderStrong,
		outlineOffset: "-1px",
	},
	menuOverlay: {
		borderRadius: radius.md,
		paddingBlock: space.x2,
		paddingInline: space.x2,
		alignItems: "center",
		backgroundColor: color.canvas,
		outlineColor: color.bgElevated,
		outlineOffset: "-2px",
		outlineStyle: "solid",
		outlineWidth: "2px",
		boxShadow: shadow.lg,
		color: color.fg,
		columnGap: space.x2,
		display: "flex",
		// gridTemplateColumns: "auto minmax(0, 1fr)",
		pointerEvents: "none",
		fontSize: fontSize.x2,
		lineHeight: lineHeight.x2,
		letterSpacing: letterSpacing.x2,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		overflow: "hidden",

		// minWidth: "12rem",
	},
	nestedAction: {
		justifySelf: "end",
	},
});
