import * as stylex from "@stylexjs/stylex";
import { breakpoints } from "@/styles/constants.stylex";
import { tokens } from "@/theme/tokens.stylex";

const activeDropTarget = ":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])";
const invalidTarget = ":is([data-invalid], [data-invalid='true'], [data-invalid=''])";

export const demoStyles = stylex.create({
	stack: {
		gap: tokens["--space-5"],
		display: "grid",
	},
	comparison: {
		gap: tokens["--space-5"],
		alignItems: "start",
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.md]: "repeat(2, minmax(0, 1fr))",
		},
	},
	panel: {
		padding: tokens["--space-4"],
		borderColor: tokens["--border"],
		borderRadius: tokens["--radius-md"],
		borderStyle: "solid",
		borderWidth: tokens["--border-width"],
		gap: tokens["--space-4"],
		backgroundColor: tokens["--surface"],
		display: "grid",
		minWidth: 0,
	},
	panelHeader: {
		gap: tokens["--space-1"],
		display: "grid",
	},
	panelFooter: {
		gap: tokens["--space-3"],
		alignItems: "center",
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "space-between",
	},
	instructions: {
		margin: 0,
		gap: tokens["--space-1"],
		color: tokens["--fg-muted"],
		fontSize: tokens["--font-size-1"],
		lineHeight: tokens["--line-height-1"],
	},
	instructionItem: {
		display: "list-item",
		listStylePosition: "inside",
		listStyleType: "auto",
		paddingInlineStart: tokens["--space-5"],
	},
	status: {
		margin: 0,
		color: tokens["--fg-muted"],
		fontSize: tokens["--font-size-1"],
		lineHeight: tokens["--line-height-1"],
	},
	workArea: {
		gap: tokens["--space-4"],
		display: "grid",
	},
	transferGrid: {
		gap: tokens["--space-3"],
		alignItems: "stretch",
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.sm]: "minmax(12rem, 0.9fr) repeat(2, minmax(10rem, 1fr))",
		},
	},
	sourceTray: {
		gap: tokens["--space-3"],
		alignContent: "start",
		display: "grid",
		minHeight: "7rem",
	},
	card: {
		padding: tokens["--space-2"],
		borderRadius: tokens["--radius-sm"],
		gap: tokens["--space-3"],
		alignItems: "center",
		backgroundColor: tokens["--elevated"],
		boxShadow: {
			default: tokens["--shadow-sm"],
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": "none",
			":hover": tokens["--shadow-md"],
		},
		color: tokens["--fg"],
		display: "flex",

		opacity: {
			default: 1,
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": 0.6,
		},
		touchAction: "none",
		transitionDuration: {
			default: "160ms",
			"@media (prefers-reduced-motion: reduce)": "0ms",
		},
		// transform: {
		// 	default: "none",
		// 	":is([data-dragging], [data-dragging='true'], [data-dragging=''])": "rotate(2deg)",
		// },
		transitionProperty: "background-color, border-color, box-shadow, opacity",
		transitionTimingFunction: "ease",
		minHeight: "3.25rem",
	},
	cardText: {
		gap: tokens["--space-1"],
		display: "grid",
		flexGrow: 1,
		minWidth: 0,
	},
	cardLabel: {
		overflow: "hidden",
		fontSize: tokens["--font-size-2"],
		fontWeight: tokens["--font-weight-medium"],
		lineHeight: tokens["--line-height-2"],
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	cardMeta: {
		color: tokens["--fg-muted"],
		fontSize: tokens["--font-size-1"],
		lineHeight: tokens["--line-height-1"],
	},
	handle: {
		padding: 0,
		borderColor: tokens["--border"],
		borderRadius: tokens["--radius-sm"],
		borderStyle: "solid",
		borderWidth: tokens["--border-width"],
		alignItems: "center",
		color: tokens["--fg-muted"],
		cursor: {
			default: "grab",
			":active": "grabbing",
		},
		display: "inline-flex",
		justifyContent: "center",
		justifySelf: "flex-end",
		marginInlineStart: "auto",
		height: tokens["--size-control-md"],
		width: tokens["--size-control-md"],
	},
	dropZone: {
		padding: tokens["--space-4"],
		borderRadius: tokens["--radius-md"],
		gap: tokens["--space-2"],
		alignItems: "stretch",
		backgroundColor: {
			[activeDropTarget]: tokens["--bg-accent"],
			default: tokens["--surface-subtle"],
			[invalidTarget]: tokens["--bg-error"],
		},
		color: tokens["--fg"],
		display: "flex",
		flexDirection: "column",
		outlineColor: {
			[activeDropTarget]: tokens["--bg-primary"],
			default: tokens["--border"],
			[invalidTarget]: tokens["--bg-error-primary"],
		},
		outlineOffset: `calc(${tokens["--border-width"]} * -1)`,
		outlineStyle: "dashed",
		outlineWidth: "1px",
		minHeight: "7rem",
	},
	dropZoneLabel: {
		fontSize: tokens["--font-size-2"],
		fontWeight: tokens["--font-weight-medium"],
		lineHeight: tokens["--line-height-2"],
	},
	dropZoneDescription: {
		color: tokens["--fg-muted"],
		fontSize: tokens["--font-size-1"],
		lineHeight: tokens["--line-height-1"],
	},
	invalidLabel: {
		color: tokens["--fg-error"],
	},
	board: {
		gap: tokens["--space-3"],
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 1fr)",
			[breakpoints.sm]: "repeat(2, minmax(0, 1fr))",
		},
	},
	column: {
		padding: tokens["--space-3"],
		borderRadius: tokens["--radius-md"],
		gap: tokens["--space-3"],
		alignContent: "start",
		backgroundColor: {
			default: tokens["--bg-inset"],
			// ":where([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": colors["--bg-highlight"],
		},
		display: "grid",
		outlineColor: {
			default: tokens["--border"],
			":focus-within": tokens["--bg-primary"],
		},
		outlineOffset: `calc(${tokens["--border-width"]} * -1)`,
		outlineStyle: "solid",
		outlineWidth: tokens["--border-width"],
		minHeight: "18rem",
	},
	columnHeader: {
		gap: tokens["--space-2"],
		alignItems: "center",
		display: "flex",
		justifyContent: "space-between",
	},
	columnTitle: {
		fontSize: tokens["--font-size-2"],
		fontWeight: tokens["--font-weight-semibold"],
		lineHeight: tokens["--line-height-2"],
	},
	columnCount: {
		color: tokens["--fg-muted"],
		fontSize: tokens["--font-size-1"],
		lineHeight: tokens["--line-height-1"],
	},
	list: {
		margin: 0,
		padding: 0,
		gap: tokens["--space-2"],
		listStyle: "none",
		display: "flex",
		flexDirection: "column",
		minHeight: "12rem",
	},
	empty: {
		// padding: space[3],
		// borderColor: colors["--fg"],
		// backgroundColor: colors["--bg-highlight"],
		// borderRadius: radius.sm,
		// borderStyle: "dashed",
		// borderWidth: border.width,
		height: "100%",
		// alignItems: "center",
		// color: colors["--fg-muted"],
		// display: "flex",
		// fontSize: fontSize.x1,
		// justifyContent: "center",
		// lineHeight: lineHeight.x1,
		// textAlign: "center",
		// minHeight: "4rem",
	},
	dropIndicator: {
		// borderRadius: radius.full,
		// marginInline: `-${space[2]}`,
		// width: `calc(100% + ${space[2]})`,
		// outline: `1px solid ${colors["--bg-primary"]}`,
		// outlineColor: colors["--bg-primary"],
		// outlineColor: "CanvasText",
		outlineStyle: {
			default: "none",
			"@media (forced-colors: active)": "solid",
		},
		outlineWidth: {
			default: 0,
			"@media (forced-colors: active)": "1px",
		},
		position: "relative",
		zIndex: 100,
		height: "0px",
		"::before": {
			borderRadius: tokens["--radius-full"],
			insetBlock: -2,
			insetInline: -16,
			backgroundColor: tokens["--bg-primary"],
			content: "",
			outlineColor: tokens["--fg-accent-contrast"],
			// outlineOffset: 2,
			outlineStyle: "solid",
			outlineWidth: 2,
			position: "absolute",
			minWidth: "100%",
		},
	},
	overlay: {
		boxShadow: tokens["--shadow-lg"],
		pointerEvents: "none",
		transform: "rotate(1deg)",
	},
	shortList: {
		gap: tokens["--space-2"],
		display: "grid",
		maxWidth: "24rem",
	},
	menuDemo: {
		alignItems: "start",
		columnGap: `calc(${tokens["--space-8"]} * 4)`,
		display: "flex",
		flexWrap: "wrap",
		position: "relative",
		rowGap: tokens["--space-3"],
		minHeight: "18rem",
	},
	sortableMenuPopup: {
		outlineColor: {
			default: "transparent",
			":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": tokens["--fg-muted"],
		},
		outlineOffset: "4px",
		outlineStyle: "dashed",
		outlineWidth: "2px",
		minWidth: "12rem",
	},
	sortableMenuItem: {
		opacity: {
			default: 1,
			":is([data-dragging], [data-dragging='true'], [data-dragging=''])": 0.58,
		},
		outlineColor: {
			default: "transparent",
			":is([data-drop-target], [data-drop-target='true'], [data-drop-target=''])": tokens["--fg"],
		},
		outlineOffset: "2px",
		outlineStyle: "dashed",
		outlineWidth: "2px",
	},
	emptyMenuItem: {
		color: tokens["--fg-muted"],
		display: "flex",
		fontStyle: "italic",
		outlineColor: tokens["--border-input"],
		outlineOffset: "-1px",
		outlineStyle: "dashed",
		outlineWidth: "1px",
	},
	menuOverlay: {
		borderRadius: tokens["--radius-md"],
		overflow: "hidden",
		paddingBlock: tokens["--space-2"],
		paddingInline: tokens["--space-2"],
		alignItems: "center",
		backgroundColor: tokens["--bg-canvas"],
		boxShadow: tokens["--shadow-lg"],
		color: tokens["--fg"],
		columnGap: tokens["--space-2"],
		display: "flex",
		fontSize: tokens["--font-size-2"],
		letterSpacing: tokens["--letter-spacing-2"],
		lineHeight: tokens["--line-height-2"],
		outlineColor: tokens["--elevated"],
		outlineOffset: "-2px",
		outlineStyle: "solid",
		outlineWidth: "2px",
		// gridTemplateColumns: "auto minmax(0, 1fr)",
		pointerEvents: "none",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",

		// minWidth: "12rem",
	},
	nestedAction: {
		justifySelf: "end",
	},
});
